set(ZEPHYR_WASM_MICRO_RUNTIME_CMAKE_DIR    ${CMAKE_CURRENT_LIST_DIR}/wasm-micro-runtime)
set(ZEPHYR_WASM_MICRO_RUNTIME_KCONFIG      ${CMAKE_CURRENT_LIST_DIR}/wasm-micro-runtime/Kconfig)

set(ZEPHYR_PROJECT_OCRE_CMAKE_DIR          ${CMAKE_CURRENT_LIST_DIR}/ocre)

set(ZEPHYR_AKIRA_MODULE_CMAKE_DIR          ${CMAKE_CURRENT_LIST_DIR}/akira)
set(ZEPHYR_AKIRA_MODULE_KCONFIG            ${CMAKE_CURRENT_LIST_DIR}/akira/Kconfig)