get_filename_component(WORKSPACE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(ZEPHYR_PROJECT_OCRE_MODULE_DIR         ${WORKSPACE_ROOT}/ocre)
set(ZEPHYR_PROJECT_OCRE_CMAKE_DIR          ${CMAKE_CURRENT_LIST_DIR}/ocre)