# west.yml - West workspace manifest
manifest: 
  projects:
    # Zephyr RTOS
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.2-branch
      west-commands: scripts/west-commands.yml
      import: true
      
    # OCRE Runtime 
    - name: project-ocre
      revision: main
      url: https://github.com/project-ocre/ocre-runtime
      path: ocre
      
  self:
    path: akira-os


