# west.yml - West workspace manifest
manifest: 
  projects:
    # Zephyr RTOS - Using v4.2.1 for ESP32 compatibility
    # v4.3.0 has POSIX timer issues on ESP32 platforms
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.2.1
      west-commands: scripts/west-commands.yml
      import: true
      
    # OCRE Runtime 
    - name: project-ocre
      revision: main
      url: https://github.com/project-ocre/ocre-runtime
      path: ocre
      
  self:
    path: akira-os


