# west.yml - West workspace manifest
manifest: 
  projects:
    # Zephyr RTOS
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v3.7-branch
      west-commands: scripts/west-commands.yml
      import: true
      
    # WASM Micro Runtime
    - name: wasm-micro-runtime
      revision: dev/zephyr_file_socket
      url: https://github.com/atym-io/wasm-micro-runtime/
      path: wasm-micro-runtime
      
    # OCRE Runtime 
    - name: project-ocre
      revision: main
      url: https://github.com/project-ocre/ocre-runtime
      path: ocre
      
  self:
    path: akira-os