# SPDX-License-Identifier: Apache-2.0

CONFIG_BOARD_AKIRA_CONSOLE=y
CONFIG_SOC_ESP32=y
CONFIG_SOC_SERIES_ESP32=y

# Enable console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Enable GPIO
CONFIG_GPIO=y

# Enable clock control
CONFIG_CLOCK_CONTROL=y

# Enable USB device
CONFIG_USB_DEVICE_STACK=y

# Enable flash
CONFIG_FLASH=y

# Enable WiFi
CONFIG_WIFI=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NETWORKING=y

# Enable minimal libc
CONFIG_MINIMAL_LIBC=y

# Clock configuration
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=240000000

# Enable FPU
CONFIG_FPU=y

# Display configuration
CONFIG_DISPLAY=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y
CONFIG_ILI9341=y

# SPI configuration
CONFIG_SPI=y
CONFIG_SPI_ESP32=y
CONFIG_SPI_2=y

# Font support
CONFIG_FONT_TERMINUS_16=y
CONFIG_FONT_TERMINUS_BOLD_16=y

# LVGL (optional if you want a GUI library)
CONFIG_LVGL=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_BTN=y


CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y


CONFIG_ESP32_WIFI_SSID="your_wifi"
CONFIG_ESP32_WIFI_PASSWORD="your_password"
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y